databases:
  - name: collaborative-whiteboard-db-fz6p
    plan: free
    databaseName: collaboard_db_16w8
    user: collaboard_user
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "18"

services:
  - type: web
    name: collaborative-whiteboard
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: BACKEND_PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: collaborative-whiteboard-db-fz6p
          property: connectionString
